name: Release Package

on:
  push:
    tags:
      - "*"

jobs:
  release_package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Extract package name from tag
        id: extract_package_name
        run: echo "::set-output name=package_name::$(echo ${GITHUB_REF#refs/tags/} | cut -d'-' -f1)"

      - name: Releasing Package
        run: pnpm nx deploy ${{ steps.extract_package_name.outputs.package_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
